$(document).ready(function(){
  $(".logo1").click(function(){
      $(".design-info").toggle();
      $(".logo1").toggle();
  });
  $(".design-info").click(function(){
      $(".logo1").toggle();
      $(".design-info").toggle();
  });
  $(".logo2").click(function(){
      $(".dev-info").toggle();
      $(".logo2").toggle();
  })
  $(".dev-info").click(function(){
      $(".logo2").toggle();
      $(".dev-info").toggle();
  });
  $(".logo3").click(function(){
      $(".product-info").toggle();
      $(".logo3").toggle();
  })
  $(".product-info").click(function(){
      $(".logo3").toggle();
      $(".product-info").toggle();
  })
  });